export default {
  startsWith: 'Начинается с',
  contains: 'Содержит',
  notContains: 'Не содержит',
  endsWith: 'Заканчивается на',
  equals: 'Равно',
  notEquals: 'Не равно',
  noFilter: 'Без фильтра',
  lt: 'Меньше чем',
  lte: 'Меньше или равно',
  gt: 'Больше чем',
  gte: 'Больше или равно',
  dateIs: 'Точная дата',
  dateIsNot: 'Дата не равна',
  dateBefore: 'Дата до',
  dateAfter: 'Дата после',
  clear: 'Очистить',
  apply: 'Применить',
  matchAll: 'Соответствует всем',
  matchAny: 'Соотвествует любому',
  addRule: 'Добавить правило',
  removeRule: 'Удалить правило',
  accept: 'Да',
  reject: 'Нет',
  choose: 'Выбрать',
  upload: 'Загрузить',
  cancel: 'Отменить',
  completed: 'Завершено',
  pending: 'В процессе',
  dayNames: [
    'Воскресенье',
    'Понедельник',
    'Вторник',
    'Среда',
    'Четверг',
    'Пятница',
    'Суббота'
  ],
  dayNamesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
  monthNames: [
    'Январь',
    'Февраль',
    'Март',
    'Апрель',
    'Май',
    'Июнь',
    'Июль',
    'Август',
    'Сентябрь',
    'Октябрь',
    'Ноябрь',
    'Декабрь'
  ],
  monthNamesShort: [
    'Янв.',
    'Февр.',
    'Март',
    'Апр.',
    'Май',
    'Июнь',
    'Июль',
    'Авг.',
    'Сент.',
    'Окт.',
    'Нояб.',
    'Дек.'
  ],
  chooseYear: 'Выберите год',
  chooseMonth: 'Выберите месяц',
  chooseDate: 'Выберите дату',
  prevDecade: 'Предыдущее десятилетие',
  nextDecade: 'Следующее десятилетие',
  prevYear: 'Предыдущий год',
  nextYear: 'Следующий год',
  prevMonth: 'Предыдущий месяц',
  nextMonth: 'Следующий месяц',
  prevHour: 'Предыдущий час',
  nextHour: 'Следующий час',
  prevMinute: 'Предыдущая минута',
  nextMinute: 'Следующая минута',
  prevSecond: 'Предыдущая секунда',
  nextSecond: 'Следующая секунда',
  am: 'до полудня',
  pm: 'после полудня',
  today: 'Сегодня',
  weekHeader: 'Нед.',
  firstDayOfWeek: 1,
  dateFormat: 'dd.mm.yy',
  weak: 'Слабый',
  medium: 'Средний',
  strong: 'Надёжный',
  passwordPrompt: 'Введите пароль',
  emptyFilterMessage: 'Ничего не найдено', // @deprecated Use 'emptySearchMessage' option instead.
  searchMessage: '{0} результатов',
  selectionMessage: '{0} элементов выбрано',
  emptySelectionMessage: 'Нет выбранного элемента',
  emptySearchMessage: 'Ничего не найдено',
  emptyMessage: 'Нет доступных опций',
  aria: {
    trueLabel: 'Верно',
    falseLabel: 'Неверно',
    nullLabel: 'Не выбрано',
    star: '1 звезда',
    stars: 'Звёзд: {star}',
    selectAll: 'Выбраны все элементы',
    unselectAll: 'Элементы не выбраны',
    close: 'Закрыть',
    previous: 'Предыдущий',
    next: 'Следующий',
    navigation: 'Навигация',
    scrollTop: 'Прокрутить вверх',
    moveTop: 'Вверх',
    moveUp: 'Поднять',
    moveDown: 'Опустить',
    moveBottom: 'Вниз',
    moveToTarget: 'Перейти к элементу',
    moveToSource: 'Перейти к источнику',
    moveAllToTarget: 'Переместить всё к элементу',
    moveAllToSource: 'Переместить всё к источнику',
    pageLabel: '{page}',
    firstPageLabel: 'Первая страница',
    lastPageLabel: 'Последняя страница',
    nextPageLabel: 'Следующая страница',
    prevPageLabel: 'Предыдущая старница',
    rowsPerPageLabel: 'Строк на странице',
    previousPageLabel: 'Предыдущая страница',
    jumpToPageDropdownLabel: 'Перейти к выпадающему списку',
    jumpToPageInputLabel: 'Перейти к полю ввода',
    selectRow: 'Строк выбрано',
    unselectRow: 'Строн не выбрано',
    expandRow: 'Строка развёрнута',
    collapseRow: 'Строка свёрнута',
    showFilterMenu: 'Показать фильтры',
    hideFilterMenu: 'Скрыть фильтры',
    filterOperator: 'Оператор фильтра',
    filterConstraint: 'Отграничение фильтра',
    editRow: 'Редактировать строку',
    saveEdit: 'Сохранить изменения',
    cancelEdit: 'Отменить редактирование',
    listView: 'Вид списком',
    gridView: 'Вид сеткой',
    slide: 'Слайд',
    slideNumber: '{slideNumber}',
    zoomImage: 'Увеличить изображение',
    zoomIn: 'Увеличить масштаб',
    zoomOut: 'Уменьшить масштаб',
    rotateRight: 'Повернуть вправо',
    rotateLeft: 'Повернуть влево'
  }
}
